name: make all

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Linux
      run: make linux
    - name: Pack Build Files
      run: |
        mkdir ~/theVaultC-linux
        mv bin/* ~/theVaultC-linux
    - name: Publish Build Files
      uses: actions/upload-artifact@v2
      with:
        path: ~/theVaultC-linux/*
        name: theVaultC-linux
  build-macos-intel:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - name: Build macOS
      run: make macX86
    - name: Pack Build Files
      run: |
        mkdir ~/theVaultC-macX86
        mv bin/* ~/theVaultC-macX86
    - name: Publish Build Files
      uses: actions/upload-artifact@v2
      with:
        path: ~/theVaultC-macX86
        name: theVaultC-macX86
  # Uncomment job once macOS 11 is available
  #build-macos-arm:

    #runs-on: macos-11.0

    #steps:
    #- uses: actions/checkout@v2
    #- name: Build macOS
      #run: make macARM
    #- name: Pack Build Files
      #run: |
        #mkdir ~/theVaultC-macARM
        #mv bin/* ~/theVaultC-macARM
    #- name: Publish Build Files
      #uses: actions/upload-artifact@v2
      #with:
        #path: ~/theVaultC-macARM
        #name: theVaultC-macARM
